default:
  image: docker:latest

stages:
  - dockerize

variables:
  GROUP_NAME: "katalog-neo"
  APP_NAME: "auth"

dockerize:master:
  stage: dockerize
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.ub.tu-dortmund.de:4567
    - docker build -t gitlab.ub.tu-dortmund.de:4567/$GROUP_NAME/$APP_NAME:latest .
    - docker push gitlab.ub.tu-dortmund.de:4567/$GROUP_NAME/$APP_NAME:latest
  only:
    - main