version: "3.8"

services:

  auth:
    image: gitlab.ub.tu-dortmund.de:4567/katalog-neo/auth:latest
    container_name: auth
    environment:
      SESSION_SECRET: ---TODO-PLEASE-ADD---
      SESSION_SALT: ---TODO-PLEASE-ADD---
      DISCOVERY_URL: ---TODO-PLEASE-ADD---
      CLIENT_ID: ---TODO-PLEASE-ADD---
      CLIENT_SECRET: ---TODO-PLEASE-ADD---
      CALLBACK_URL: ---TODO-PLEASE-ADD---
      CLIENT_ID_ROPC: ---TODO-PLEASE-ADD---
      CLIENT_SECRET_ROPC: ---TODO-PLEASE-ADD---
      JWK_URL: ---TODO-PLEASE-ADD---
    logging:
      driver: "journald"
    restart: unless-stopped
    ports:
      - 3200:3000
